**Numpy:**

Numpy is a Python library for scientific computing that supports multi-dimensional arrays and their manipulation.


**Why Numpy over lists?**

* Lists are faster than Numpy

  * Lists can store multiple data types at once, but Numpy doesn't. So every element in a numpy array need not undergo type checking.
  * Numpy stores data in fixed type ie. 5 is stored as 00000101 (int32 type) always. Whereas storing of elements in lists require a lot of meta data like Size, Object Type, Object Value, Reference Count, this means every element takes up much more space. Thus due to the larger space, lists are slower than numpy. 

* Lists are scattered in memory. But numpy uses contiguous memory. 
 * Allows SIMD (Single Input Multiple Data) vector processing
 * Better Cache utilization 




Importing Numpy Library

In [3]:
import numpy as np

In [4]:
# Creating a Simple 1-D array
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
# Creating 2-D array 
a= np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [6]:
print(a.ndim)

2


In [8]:
print(a.shape)

(2, 2)


In [12]:
print(a.dtype)
print(a.itemsize)

float64
8


In [13]:
# By default int32 is used. we can assign our own datatype while creating the array
b = np.array([1, 2, 3], dtype = "int16")
print(b.dtype)
print(b.itemsize) # Size of elements in bytes

int16
2


In [14]:
## Number of elements in array
print(b.size)

## Memory size of array 
print(b.nbytes)

3
6


**Manipulating Numpy array**

In [18]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13 ,14, 15]])
print(a)
print(a.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)


In [29]:
# Accessing a specific element. NOTE: Numpy arrays are 0-indexed
print(a[2, 3])

# Accessing a full row: 
print(a[1, :])

# Accessing full column:
print(a[:, 1])

# Numpy allows negative indexing like lists
print(a[1, -1]) # first row, last element 

# Accessing a range of elements
print(a[0:2, 1:-2]) ## The closing index is not included

#Accessing a range of values by steps
print(a[: , ::2]) # accessing every 2nd element

# Changing an element
print(a[1, 2])
a[1,2] = 3
print(a[1, 2])

# Changing values of a series of elements

print(a[: , 1:3])
a[: , 1:3] = [1, 2]
print(a[: , 1:3])

# lesser assignment than available length
print(a[: , 1:4])
a[: , 1:4] = [1, 2] # Throws an error due to input size mismatch
print(a[: , 1:4])

14
[ 6  1  2  9 10]
[1 1 1]
10
[[1 2]
 [1 2]]
[[ 1  2  5]
 [ 6  2 10]
 [11  2 15]]
2
3
[[1 2]
 [1 3]
 [1 2]]
[[1 2]
 [1 2]
 [1 2]]
[[ 1  2  4]
 [ 1  2  9]
 [ 1  2 14]]


ValueError: ignored

3-D array example 

In [34]:
b = np.array([[[1, 2], [3, 4]], [[4, 5], [6, 7]]])
print(b.ndim)

# accessing elements works outside in. 

b[1, : , 1] = [11, 12]
print(b)

3
[[[ 1  2]
  [ 3  4]]

 [[ 4 11]
  [ 6 12]]]


**Initializing different types of arrays**

In [39]:
# all zeros
np.zeros((10))
np.zeros((3, 2, 2), dtype = 'int32')

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int32)

In [41]:
# all ones
np.ones((2, 2, 2, 3 ), dtype="int16")

array([[[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]]], dtype=int16)

In [45]:
# All elements of a particular number 
np.full((5,5), 10)
np.full(a.shape, 11)

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

In [46]:
## similar to full, full_like
np.full_like(a, 12) # copies the shape of the existing matrix with the values given by the user

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [48]:
## Creating a random decimal array 
np.random.rand(2,2,2)

array([[[0.09851074, 0.16445346],
        [0.79898931, 0.48765163]],

       [[0.50968848, 0.4890359 ],
        [0.88120974, 0.20051059]]])

In [51]:
### creating a random integer array 
np.random.randint(2, 15, size = (2, 2, 2))

array([[[ 8, 14],
        [ 3, 13]],

       [[ 6,  5],
        [ 3, 12]]])

In [52]:
## Creating an identity matrix 
np.identity(5) # The identity matrix by nature is square shaped

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
### Repeating an array 
a = np.array([[1, 2, 3]])
output = np.repeat(a, 3, axis=0) #axis = 0, represents rows and axis = 1 represents columns 
print(output)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


**Exercise 1** 

1 1 1 1 1

1 0 0 0 1

1 0 9 0 1

1 0 0 0 1

1 1 1 1 1

Create the above array using numpy (not mannualy)

In [63]:
matrix = np.ones((5, 5), dtype = "int32")
sub_matrix = np.zeros((3, 3), dtype = "int32")
matrix[1:4, 1:4] = sub_matrix

matrix[2, 2]=9

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Making a new copy of an array (Careful)

In [66]:
a = np.array([1, 2, 3])
b = a
b[1] = 100
print(a[1])

## When we do b=a, we are just making b point to the adress of a. we didn't make a new copy.

## To make a new cophy of array use a.copy()
a = np.array([1, 2, 3])
b = a.copy()
b[1] = 100
print(a[1])

100
2


**Element wise operations**


In [74]:
a = np.array([1, 2, 3, 4])
print(a+1)
print(a-1)
print(a/1)
print(a*2)
print(a**2)
print(a**3)
print(a%2)
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))


b= np.array([1,2,3,4])
print(a*b)

[2 3 4 5]
[0 1 2 3]
[1. 2. 3. 4.]
[2 4 6 8]
[ 1  4  9 16]
[ 1  8 27 64]
[1 0 1 0]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]
[ 1  4  9 16]


**Matrix calculations**

In [85]:
a = np.array([[1,2, 3], [1, 2, 3]])
b = np.ones((3,3))
print(np.matmul(a, b)) # Matrix multiplication

print(np.linalg.det(b)) # matrix determinant calculation

[[6. 6. 6.]
 [6. 6. 6.]]
0.0


**Statistics Functions**

In [90]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.max(a, axis = 0))
print(np.max(a, axis = 1))

print(a.shape)
b= a.reshape((4,3)) # reshape is not inplace, we have to explicitly store it into a new result array 
print(b)

1
12
78
[ 9 10 11 12]
[ 4  8 12]
(3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Horizontal and Vertical Stacking**

In [94]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack([a,b, a, b, a])) # The arrangement of arrays inside the stack must always be passed as a list

print(np.hstack([a,b,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]]
[1 2 3 4 5 6 1 2 3]


**Load Data From File**

In [98]:
data = np.genfromtxt('Sample_Data.txt', delimiter=",")
print(data)
print(data.dtype)
data = data.astype('int32')
print(data.dtype)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
float64
int32


**Boolean Masking and Advanced indexing**

In [103]:
print(data > 5)
print((data % 2 ==0) & (data > 5))
print(data[(data % 2 ==0) & (data > 5)])

[[False False False False False]
 [ True  True  True  True  True]]
[[False False False False False]
 [ True False  True False  True]]
[ 6  8 10]
